function [ st ] = rfilestructs( type, varargin )
%RFILESTRUCTS returns a structure object 
%   This function objective is to allow easy access to structure
%   declaration in order to improve code reading
%
%   INPUT
%   TYPE - Type of structure to be returned
%   NEPOCH - Number of entries to figure in the matrix
%
%   OUTPUT
%   ST - Structure object
%
% Pedro Silva, Instituto Superior Tecnico, January 2012

    % CHECK INPUTS
    if ~ischar(type), 
        error('rfilestructs: TYPE must be a string'); 
    end;
    
    if nargin == 2
        nEpoch = varargin{1};
        if ~isscalar(nEpoch)
            error('rfilestructs: nEpoch must be a scalar'); 
        end
    end
    
    if strcmpi(type,'ranges')
       satNo  = userparams('MAXSAT');
       st     = struct('PRL1', zeros(nEpoch,satNo),'CPL1', zeros(nEpoch,satNo),...
                       'PRL2', zeros(nEpoch,satNo),'CPL2', zeros(nEpoch,satNo),...
                       'PRCA', zeros(nEpoch,satNo),'CPCA', zeros(nEpoch,satNo),...
                       'TOW' , zeros(nEpoch,1),'SATAZ',[],'SATELV',[]);  
                   
    elseif strcmpi(type,'binranges')
        satNo = userparams('MAXSAT');
        st    = struct(...
                       'WARNINGCA', zeros(nEpoch,satNo),'QUALITYCA', zeros(nEpoch,satNo),...               
                       'SNRCA', zeros(nEpoch,satNo),'CPCA', zeros(nEpoch,satNo),...               
                       'PRCA', zeros(nEpoch,satNo),'DOCA', zeros(nEpoch,satNo),...
                       'BFCA', zeros(nEpoch,satNo),...
                       'WARNINGL1', zeros(nEpoch,satNo),'QUALITYL1', zeros(nEpoch,satNo),...               
                       'SNRL1', zeros(nEpoch,satNo),'CPL1', zeros(nEpoch,satNo),...               
                       'PRL1', zeros(nEpoch,satNo),'DOL1', zeros(nEpoch,satNo),...
                       'BFL1', zeros(nEpoch,satNo),...
                       'WARNINGL2', zeros(nEpoch,satNo),'QUALITYL2', zeros(nEpoch,satNo),...               
                       'SNRL2', zeros(nEpoch,satNo),'CPL2', zeros(nEpoch,satNo),...               
                       'PRL2', zeros(nEpoch,satNo),'DOL2', zeros(nEpoch,satNo),...
                       'BFL2', zeros(nEpoch,satNo),...
                       'SATELV', zeros(nEpoch,satNo),'SATAZ', zeros(nEpoch,satNo),...
                       'SATLIST', zeros(nEpoch,satNo),...
                       'SEQGLO',zeros(nEpoch,1),'TOWGLO',zeros(nEpoch,1),...
                       'SEQ',zeros(nEpoch,1), 'TOW', zeros(nEpoch,1), ...
                       'WN', 0);  
        

    elseif strcmpi(type,'bineph')
        ArgsNo = userparams('EPHARGS'); % Number of arguments in the eph message
        SatNo  = userparams('MAXSAT'); % Number of satellites    
        st     = struct('data',zeros(ArgsNo+1,SatNo)); % +1 for TOW
    end

end

