all: example1.bin example2.bin example3.bin example4.bin

example1.bin: example1.cpp
	g++ -o example1.bin example1.cpp

example2.bin: example2.cpp
	g++ -o example2.bin example2.cpp

example3.bin: example3.cpp
	g++ -o example3.bin example3.cpp

example4.bin: example4.cpp
	g++ -o example4.bin example4.cpp

clean:
	rm *.o *~ *.bin
